### PR TITLE
Fix NordicSPP OOM

### PR DESCRIPTION
**Pull request by alberk8**
## Description

Fix OOM on start of spp.Start("nanoFrameworkSerial") 

## Motivation and Context

- Fixes nanoFramework/Home#1261

## How Has This Been Tested?

Run with Bluetooth NordicSPP Sample 

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [x] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (add new Unit Test(s) or improved existing one(s), has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [ ] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/master/CONTRIBUTING.md) document.
- [ ] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).
- [ ] I have added new tests to cover my changes.

### CODE REVIEW

**Comment by AdrianSoundy** [comment]
I assume the OOM issue is Out Of Memory.
This bit of NordisSPP code is just creating a new service and shouldn't require the BluetoothLEServer to be created before the GattServiceProvider.Create() as it will be created in the call anyway. I think the only reason this is working is due to the order memory allocations being changed. So memory must be really tight. Must be a firmware without psram. This also means that any app that just calls GattServiceProvider.Create() would have same problem.

Maybe a better way would be to try and make more memory available by restricting the bluetooth config further for these firmwares. Less connections etc,

**Review by Ellerbach — APPROVED** [review]
Looks good to me!

**Comment by alberk8** [comment]
> I assume the OOM issue is Out Of Memory. This bit of NordisSPP code is just creating a new service and shouldn't require the BluetoothLEServer to be created before the GattServiceProvider.Create() as it will be created in the call anyway. I think the only reason this is working is due to the order memory allocations being changed. So memory must be really tight. Must be a firmware without psram. This also means that any app that just calls GattServiceProvider.Create() would have same problem.
> 
> Maybe a better way would be to try and make more memory available by restricting the bluetooth config further for these firmwares. Less connections etc,

In fact the OOM coming back from the native code is not due to memory.  I trace it to [this](https://github.com/nanoframework/nf-interpreter/blob/84f9c23213e117aaab0cca3ecff238f8541be00a/targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/sys_dev_ble_native_nanoFramework_Device_Bluetooth_GenericAttributeProfile_GattServiceProvider.cpp#L649) where the arraylist passed from managed code is empty.

**Comment by AdrianSoundy** [comment]
@alberk8 
If that's the case I will need to look at this deeper as the solution you provided shouldn't be needed.
Looks like a deeper issue.

**Comment by stefanomerotta** [comment]
The deeper issue could be the cause also of this: [Unable to Advertise Custom BLE service that was created without characteristics](https://github.com/nanoframework/Home/issues/1250)

**Comment by AdrianSoundy** [comment]
@alberk8 
I looked at this problem and it due to a bug when the BluetoothLEServer instance is created

To fix problem remove Line 68 in BluetoothLEServer
```
            _services = new();
```
It was clearing the _services arraylist which already had entries in it causing the start advertising to run without any services. 
Creating instance at start avoided that.

Once you have removed other change and added this change we can get this merged

**Review by AdrianSoundy — APPROVED** [review]
All looks good to me

**Comment by AdrianSoundy** [comment]
@josesimoes 
Any idea why we are getting a build error ?

**Comment by josesimoes** [comment]
> @josesimoes Any idea why we are getting a build error ?

Transient error from a timeout or temporary failure on the service.... I've just re-run the job.

**Pull request merged**
